# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilePropetiesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilePropetiesDialog(object):
    def setupUi(self, FilePropetiesDialog):
        FilePropetiesDialog.setObjectName("FilePropetiesDialog")
        FilePropetiesDialog.resize(412, 419)
        FilePropetiesDialog.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.buttonOK = QtWidgets.QDialogButtonBox(FilePropetiesDialog)
        self.buttonOK.setGeometry(QtCore.QRect(161, 371, 93, 28))
        self.buttonOK.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonOK.setObjectName("buttonOK")
        self.layoutWidget = QtWidgets.QWidget(FilePropetiesDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 391, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.labelExecutableOrEmpty = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelExecutableOrEmpty.setFont(font)
        self.labelExecutableOrEmpty.setAlignment(QtCore.Qt.AlignCenter)
        self.labelExecutableOrEmpty.setObjectName("labelExecutableOrEmpty")
        self.gridLayout.addWidget(self.labelExecutableOrEmpty, 3, 1, 1, 1)
        self.labelLastModified = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLastModified.setFont(font)
        self.labelLastModified.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLastModified.setObjectName("labelLastModified")
        self.gridLayout.addWidget(self.labelLastModified, 2, 1, 1, 1)
        self.labelFileName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFileName.setFont(font)
        self.labelFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileName.setObjectName("labelFileName")
        self.gridLayout.addWidget(self.labelFileName, 0, 1, 1, 1)
        self.labelFileOrFolder = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFileOrFolder.setFont(font)
        self.labelFileOrFolder.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileOrFolder.setObjectName("labelFileOrFolder")
        self.gridLayout.addWidget(self.labelFileOrFolder, 0, 0, 1, 1)
        self.labelFileSize = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFileSize.setFont(font)
        self.labelFileSize.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileSize.setObjectName("labelFileSize")
        self.gridLayout.addWidget(self.labelFileSize, 1, 1, 1, 1)
        FilePropetiesDialog.setWindowFlags(
        QtCore.Qt.Window |
        QtCore.Qt.CustomizeWindowHint |
        QtCore.Qt.WindowTitleHint |
        QtCore.Qt.WindowCloseButtonHint |
        QtCore.Qt.WindowStaysOnTopHint
        )

        self.retranslateUi(FilePropetiesDialog)
        QtCore.QMetaObject.connectSlotsByName(FilePropetiesDialog)

    def retranslateUi(self, FilePropetiesDialog):
        _translate = QtCore.QCoreApplication.translate
        FilePropetiesDialog.setWindowTitle(_translate("FilePropetiesDialog", "File/Folder Propeties"))
        self.label_6.setText(_translate("FilePropetiesDialog", "Is Executable? :"))
        self.label_4.setText(_translate("FilePropetiesDialog", "Last Modified : "))
        self.label_3.setText(_translate("FilePropetiesDialog", "Size (in MB) : "))
        self.labelExecutableOrEmpty.setText(_translate("FilePropetiesDialog", "FileName"))
        self.labelLastModified.setText(_translate("FilePropetiesDialog", "FileName"))
        self.labelFileName.setText(_translate("FilePropetiesDialog", "FileName"))
        self.labelFileOrFolder.setText(_translate("FilePropetiesDialog", "File/Folder Name : "))
        self.labelFileSize.setText(_translate("FilePropetiesDialog", "Size"))
