# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeEditDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeEditDialog(object):
    def setupUi(self, TimeEditDialog):
        TimeEditDialog.setObjectName("TimeEditDialog")
        TimeEditDialog.resize(326, 240)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(TimeEditDialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(70, 110, 169, 24))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.labelFileName = QtWidgets.QLabel(TimeEditDialog)
        self.labelFileName.setGeometry(QtCore.QRect(110, 70, 85, 18))
        self.labelFileName.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelFileName.setFont(font)
        self.labelFileName.setObjectName("labelFileName")
        self.splitter = QtWidgets.QSplitter(TimeEditDialog)
        self.splitter.setGeometry(QtCore.QRect(70, 170, 186, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.setButton = QtWidgets.QPushButton(self.splitter)
        self.setButton.setMaximumSize(QtCore.QSize(90, 28))
        self.setButton.setObjectName("setButton")
        self.cancelButton = QtWidgets.QPushButton(self.splitter)
        self.cancelButton.setMaximumSize(QtCore.QSize(90, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(TimeEditDialog)
        self.label.setGeometry(QtCore.QRect(80, 40, 149, 18))
        self.label.setMaximumSize(QtCore.QSize(149, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(TimeEditDialog)
        self.cancelButton.clicked.connect(TimeEditDialog.close)
        QtCore.QMetaObject.connectSlotsByName(TimeEditDialog)

    def retranslateUi(self, TimeEditDialog):
        _translate = QtCore.QCoreApplication.translate
        TimeEditDialog.setWindowTitle(_translate("TimeEditDialog", "Set Last Modified Time"))
        self.labelFileName.setText(_translate("TimeEditDialog", "Filename. txt"))
        self.setButton.setText(_translate("TimeEditDialog", "Set"))
        self.cancelButton.setText(_translate("TimeEditDialog", "Cancel"))
        self.label.setText(_translate("TimeEditDialog", "Change Last Modified:-"))
